// D-21/§8.3: the 8-layer 256² material texture array, generated by compute
// at startup. Mip N+1 is built from mip N by decoding sRGB to linear,
// averaging, and re-encoding. Sampling goes through an explicit -srgb view
// so filtering happens in linear space.
import texgenSrc from './shaders/texgen.wgsl?raw';

export const TEXTURE_SIZE = 256;
export const TEXTURE_LAYERS = 8;
const MIP_COUNT = 9; // log2(256) + 1

export async function createMaterialTextures(device: GPUDevice): Promise<{
  texture: GPUTexture;
  sampleView: GPUTextureView;
}> {
  const texture = device.createTexture({
    size: [TEXTURE_SIZE, TEXTURE_SIZE, TEXTURE_LAYERS],
    format: 'rgba8unorm',
    mipLevelCount: MIP_COUNT,
    viewFormats: ['rgba8unorm-srgb'],
    usage: GPUTextureUsage.STORAGE_BINDING | GPUTextureUsage.TEXTURE_BINDING,
  });

  const module = device.createShaderModule({ code: texgenSrc });
  const genPipeline = await device.createComputePipelineAsync({
    layout: 'auto',
    compute: { module, entryPoint: 'cs_main' },
  });
  const mipPipeline = await device.createComputePipelineAsync({
    layout: 'auto',
    compute: { module, entryPoint: 'cs_mip' },
  });

  const encoder = device.createCommandEncoder();

  {
    const pass = encoder.beginComputePass();
    pass.setPipeline(genPipeline);
    pass.setBindGroup(
      0,
      device.createBindGroup({
        layout: genPipeline.getBindGroupLayout(0),
        entries: [
          {
            binding: 0,
            resource: texture.createView({
              dimension: '2d-array',
              baseMipLevel: 0,
              mipLevelCount: 1,
            }),
          },
        ],
      }),
    );
    pass.dispatchWorkgroups(TEXTURE_SIZE / 8, TEXTURE_SIZE / 8, TEXTURE_LAYERS);
    pass.end();
  }

  for (let mip = 1; mip < MIP_COUNT; mip++) {
    const pass = encoder.beginComputePass();
    pass.setPipeline(mipPipeline);
    pass.setBindGroup(
      0,
      device.createBindGroup({
        layout: mipPipeline.getBindGroupLayout(0),
        entries: [
          {
            binding: 0,
            resource: texture.createView({
              dimension: '2d-array',
              baseMipLevel: mip,
              mipLevelCount: 1,
            }),
          },
          {
            binding: 1,
            resource: texture.createView({
              dimension: '2d-array',
              baseMipLevel: mip - 1,
              mipLevelCount: 1,
            }),
          },
        ],
      }),
    );
    const size = Math.max(1, TEXTURE_SIZE >> mip);
    pass.dispatchWorkgroups(Math.ceil(size / 8), Math.ceil(size / 8), TEXTURE_LAYERS);
    pass.end();
  }

  device.queue.submit([encoder.finish()]);

  return {
    texture,
    // §8.3: the sRGB view restricts usage to TEXTURE_BINDING — the srgb
    // view format cannot carry the texture's STORAGE_BINDING usage.
    sampleView: texture.createView({
      dimension: '2d-array',
      format: 'rgba8unorm-srgb',
      usage: GPUTextureUsage.TEXTURE_BINDING,
    }),
  };
}
