import { createLibp2p } from 'libp2p'
import { webRTC } from '@libp2p/webrtc'
import { webSockets } from '@libp2p/websockets'
import { circuitRelayTransport } from '@libp2p/circuit-relay-v2'
import { gossipsub } from '@chainsafe/libp2p-gossipsub'
import { bootstrap } from '@libp2p/bootstrap'
import { identify } from '@libp2p/identify'
import { noise } from '@chainsafe/libp2p-noise'
import { yamux } from '@chainsafe/libp2p-yamux'
globalThis.x = () => createLibp2p({ transports:[webRTC(),webSockets(),circuitRelayTransport()], connectionEncrypters:[noise()], streamMuxers:[yamux()], peerDiscovery:[bootstrap({list:[]})], services:{identify:identify(), pubsub:gossipsub()} })
